using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LegacyLens.Analysis;

/// <summary>Measured facts about one source file. Nothing here is an opinion.</summary>
public record FileMetrics(
    string Path,
    int Lines,
    /// <summary>Lines that are neither blank nor comment-only.</summary>
    int CodeLines,
    int Types,
    int Methods,
    /// <summary>Cyclomatic complexity summed over every method in the file.</summary>
    int Complexity,
    /// <summary>Complexity of the single worst method, and its name.</summary>
    int WorstMethodComplexity,
    string? WorstMethod,
    /// <summary>Deepest nesting of blocks anywhere in the file.</summary>
    int MaxNesting,
    /// <summary>
    /// Written by a tool rather than a person. Reported so that rankings can
    /// exclude it: a WSDL proxy with 1,944 methods tops every complexity chart
    /// and tells the reader nothing they can act on.
    /// </summary>
    bool IsGenerated,
    /// <summary>
    /// A test file. Excluded from risk rankings: ranking tests by how risky
    /// they are, and noting that nothing tests them, is noise.
    /// </summary>
    bool IsTest);

/// <summary>
/// Measures source files with Roslyn's parser and nothing else.
///
/// Syntax trees only: no compilation, no resolved symbols, no restored
/// packages. That costs the ability to answer "what type is this expression",
/// and buys the ability to read a solution that does not build, which is the
/// usual state of code somebody has just inherited.
/// </summary>
public class CodeMetrics
{
    public FileMetrics Measure(string path, string source)
    {
        var tree = CSharpSyntaxTree.ParseText(source);
        var root = tree.GetRoot();

        var walker = new Walker();
        walker.Visit(root);

        var lines = source.Split('\n').Length;

        return new FileMetrics(
            path,
            lines,
            CountCodeLines(source),
            walker.Types,
            walker.Methods,
            walker.TotalComplexity,
            walker.WorstComplexity,
            walker.WorstMethod,
            walker.MaxNesting,
            LooksGenerated(path, source, walker.HasGeneratedAttribute),
            LooksLikeTest(path, walker.HasTestAttribute));
    }

    public FileMetrics? MeasureFile(string path)
    {
        try
        {
            return Measure(path, File.ReadAllText(path));
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return null;
        }
    }

    /// <summary>Folders that hold nothing but tool output.</summary>
    private static readonly string[] GeneratedFolders =
        ["Web References", "Service References", "Connected Services"];

    /// <summary>
    /// Whether a person wrote this file.
    ///
    /// Three signals, any one of which is enough. The header comment is the
    /// convention Microsoft's own generators follow; the attribute is what the
    /// compiler and analysers look for; the folders are where Visual Studio
    /// drops SOAP proxies.
    ///
    /// Only the first lines are scanned for the comment: a generator writes its
    /// banner at the top, and reading a 12,000 line proxy to look for it would
    /// cost more than the whole analysis.
    /// </summary>
    internal static bool LooksGenerated(string path, string source, bool hasAttribute)
    {
        if (hasAttribute) return true;

        var normalised = path.Replace('\\', '/');
        if (GeneratedFolders.Any(f => normalised.Contains(f, StringComparison.OrdinalIgnoreCase)))
            return true;

        if (normalised.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase)
            || normalised.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || normalised.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase))
            return true;

        var head = source.Length > 2_000 ? source[..2_000] : source;
        return head.Contains("auto-generated", StringComparison.OrdinalIgnoreCase)
            || head.Contains("autogenerated", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Whether this file contains tests.
    ///
    /// The attribute is the reliable signal, since xUnit, NUnit and MSTest all
    /// mark their tests. The path is a fallback for helpers and fixtures that
    /// sit beside the tests without carrying an attribute themselves.
    /// </summary>
    internal static bool LooksLikeTest(string path, bool hasTestAttribute)
    {
        if (hasTestAttribute) return true;

        var normalised = path.Replace('\\', '/');
        var name = System.IO.Path.GetFileNameWithoutExtension(normalised);

        return name.EndsWith("Tests", StringComparison.OrdinalIgnoreCase)
            || name.EndsWith("Test", StringComparison.OrdinalIgnoreCase)
            || name.EndsWith("Spec", StringComparison.OrdinalIgnoreCase)
            || normalised.Contains("/tests/", StringComparison.OrdinalIgnoreCase)
            || normalised.Contains("/test/", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Lines that carry code, ignoring blanks and comment-only lines.
    ///
    /// Deliberately naive: a "//" inside a string literal counts as a comment
    /// here. Getting that exactly right needs the full lexer for a number whose
    /// only use is comparing files to each other, where a consistent small
    /// error changes no ranking.
    /// </summary>
    private static int CountCodeLines(string source)
    {
        var count = 0;
        var inBlockComment = false;

        foreach (var raw in source.Split('\n'))
        {
            var line = raw.Trim();

            if (inBlockComment)
            {
                if (line.Contains("*/")) inBlockComment = false;
                continue;
            }

            if (line.Length == 0 || line.StartsWith("//")) continue;

            if (line.StartsWith("/*"))
            {
                if (!line.Contains("*/")) inBlockComment = true;
                continue;
            }

            count++;
        }

        return count;
    }

    /// <summary>
    /// Walks the syntax tree accumulating the counts.
    ///
    /// Cyclomatic complexity is the count of decision points plus one. Each
    /// branch, loop, catch, case and short-circuiting operator adds a path
    /// through the method, and the number is a proxy for how many cases a test
    /// suite would have to cover.
    /// </summary>
    private sealed class Walker : CSharpSyntaxWalker
    {
        private int _nesting;
        private int _currentComplexity;
        private string? _currentMethod;

        public int Types { get; private set; }
        public int Methods { get; private set; }
        public int TotalComplexity { get; private set; }
        public int WorstComplexity { get; private set; }
        public string? WorstMethod { get; private set; }
        public int MaxNesting { get; private set; }
        public bool HasGeneratedAttribute { get; private set; }
        public bool HasTestAttribute { get; private set; }

        private static readonly string[] TestAttributes =
            ["Fact", "Theory", "Test", "TestMethod", "TestCase", "TestFixture"];

        public override void VisitAttribute(AttributeSyntax node)
        {
            var name = node.Name.ToString();

            // Matches both GeneratedCode and GeneratedCodeAttribute, qualified
            // or not, since source generators and WSDL write it differently.
            if (name.Contains("GeneratedCode", StringComparison.Ordinal))
                HasGeneratedAttribute = true;

            var simple = name.Split('.')[^1];
            if (TestAttributes.Contains(simple, StringComparer.Ordinal)
                || TestAttributes.Contains(simple.Replace("Attribute", ""), StringComparer.Ordinal))
                HasTestAttribute = true;

            base.VisitAttribute(node);
        }

        public override void VisitClassDeclaration(ClassDeclarationSyntax node)
        {
            Types++;
            base.VisitClassDeclaration(node);
        }

        public override void VisitStructDeclaration(StructDeclarationSyntax node)
        {
            Types++;
            base.VisitStructDeclaration(node);
        }

        public override void VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
        {
            Types++;
            base.VisitInterfaceDeclaration(node);
        }

        public override void VisitRecordDeclaration(RecordDeclarationSyntax node)
        {
            Types++;
            base.VisitRecordDeclaration(node);
        }

        public override void VisitMethodDeclaration(MethodDeclarationSyntax node)
        {
            EnterMember(node.Identifier.Text, () => base.VisitMethodDeclaration(node));
        }

        public override void VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
        {
            EnterMember($"{node.Identifier.Text} (ctor)", () => base.VisitConstructorDeclaration(node));
        }

        public override void VisitAccessorDeclaration(AccessorDeclarationSyntax node)
        {
            // A property accessor with a body is a method in every way that
            // matters here, and legacy code hides a great deal inside them.
            if (node.Body is null && node.ExpressionBody is null)
            {
                base.VisitAccessorDeclaration(node);
                return;
            }

            var property = node.FirstAncestorOrSelf<PropertyDeclarationSyntax>();
            EnterMember($"{property?.Identifier.Text}.{node.Keyword.Text}",
                        () => base.VisitAccessorDeclaration(node));
        }

        private void EnterMember(string name, Action visit)
        {
            // Local functions and nested lambdas would otherwise reset the
            // enclosing method's tally.
            var outerComplexity = _currentComplexity;
            var outerName = _currentMethod;

            Methods++;
            _currentComplexity = 1;      // one path through, before any branch
            _currentMethod = name;

            visit();

            if (_currentComplexity > WorstComplexity)
            {
                WorstComplexity = _currentComplexity;
                WorstMethod = _currentMethod;
            }
            TotalComplexity += _currentComplexity;

            _currentComplexity = outerComplexity;
            _currentMethod = outerName;
        }

        // ---- decision points ------------------------------------------

        public override void VisitIfStatement(IfStatementSyntax node)
        {
            _currentComplexity++;
            Nested(() => base.VisitIfStatement(node));
        }

        public override void VisitWhileStatement(WhileStatementSyntax node)
        {
            _currentComplexity++;
            Nested(() => base.VisitWhileStatement(node));
        }

        public override void VisitForStatement(ForStatementSyntax node)
        {
            _currentComplexity++;
            Nested(() => base.VisitForStatement(node));
        }

        public override void VisitForEachStatement(ForEachStatementSyntax node)
        {
            _currentComplexity++;
            Nested(() => base.VisitForEachStatement(node));
        }

        public override void VisitDoStatement(DoStatementSyntax node)
        {
            _currentComplexity++;
            Nested(() => base.VisitDoStatement(node));
        }

        public override void VisitCatchClause(CatchClauseSyntax node)
        {
            _currentComplexity++;
            Nested(() => base.VisitCatchClause(node));
        }

        public override void VisitSwitchSection(SwitchSectionSyntax node)
        {
            // Each label is a separate path; "case 1: case 2:" falling through
            // to one body is two.
            _currentComplexity += node.Labels.Count;
            Nested(() => base.VisitSwitchSection(node));
        }

        public override void VisitSwitchExpressionArm(SwitchExpressionArmSyntax node)
        {
            _currentComplexity++;
            base.VisitSwitchExpressionArm(node);
        }

        public override void VisitConditionalExpression(ConditionalExpressionSyntax node)
        {
            _currentComplexity++;
            base.VisitConditionalExpression(node);
        }

        public override void VisitBinaryExpression(BinaryExpressionSyntax node)
        {
            // Short-circuiting operators branch; arithmetic does not.
            if (node.IsKind(SyntaxKind.LogicalAndExpression) ||
                node.IsKind(SyntaxKind.LogicalOrExpression) ||
                node.IsKind(SyntaxKind.CoalesceExpression))
            {
                _currentComplexity++;
            }
            base.VisitBinaryExpression(node);
        }

        private void Nested(Action visit)
        {
            _nesting++;
            if (_nesting > MaxNesting) MaxNesting = _nesting;
            visit();
            _nesting--;
        }
    }
}
