using System.Reflection;
using System.Text;

namespace LegacyLens.Characterization;

/// <summary>One method, and everything observed about it.</summary>
public record Characterized(Target Target, IReadOnlyList<Observation> Observations);

/// <summary>One generated test, tied back to what it was written from.</summary>
public record GeneratedCase(string TestName, Target Target, Observation Observation);

/// <summary>
/// A generated file and its contents, described.
///
/// The cases travel with the source because verification runs the file and
/// reports failures by test name. Without the mapping back, a single failing
/// case would mean discarding the whole suite instead of the one assertion
/// that turned out to be wrong.
/// </summary>
public record GeneratedSuite(string Source, IReadOnlyList<GeneratedCase> Cases);

/// <summary>
/// Writes the observations out as a compilable xUnit class.
///
/// The generated file states what it is at the top, in the plainest available
/// terms. Someone will find it in six months during a failure, and what they
/// need first is that these assertions record old behaviour rather than
/// intended behaviour: a failure here means something changed, not that
/// something is wrong.
/// </summary>
public class TestWriter
{
    public string Namespace { get; init; } = "Characterized";

    /// <summary>
    /// Stamped into the header. Injectable so a test can assert on the whole
    /// file, and so a regenerated suite does not churn on the clock alone.
    /// </summary>
    public DateTimeOffset GeneratedAt { get; init; } = DateTimeOffset.UtcNow;

    public GeneratedSuite Write(Type subject, IReadOnlyList<Characterized> methods)
    {
        var source = new StringBuilder();
        var className = $"{subject.Name}Characterization";

        source.AppendLine("// <auto-generated>");
        source.AppendLine("//");
        source.AppendLine($"// Characterization tests for {subject.FullName}, recorded by");
        source.AppendLine($"// Legacy Lens on {GeneratedAt:yyyy-MM-dd}.");
        source.AppendLine("//");
        source.AppendLine("// These assertions were not written by anyone. They were produced by");
        source.AppendLine("// calling the code and writing down what it did, so they describe how");
        source.AppendLine("// it behaved on that day and not how it is supposed to behave. A");
        source.AppendLine("// failure here means the behaviour changed. Whether that change is a");
        source.AppendLine("// fix or a regression is not something this file knows: if the old");
        source.AppendLine("// behaviour was a bug, this file faithfully recorded the bug.");
        source.AppendLine("//");
        source.AppendLine("// They exist to make a migration verifiable. Delete them once the");
        source.AppendLine("// code they cover has tests that state an intention.");
        source.AppendLine("// </auto-generated>");
        source.AppendLine();
        source.AppendLine("using System.Text.Json;");
        source.AppendLine("using Xunit;");
        source.AppendLine();
        source.AppendLine($"namespace {Namespace};");
        source.AppendLine();
        source.AppendLine($"public class {className}");
        source.AppendLine("{");

        var used = new Dictionary<string, int>();
        var cases = new List<GeneratedCase>();

        foreach (var method in methods)
        {
            foreach (var observation in method.Observations)
            {
                // The blank line goes before each case except the first, which
                // leaves no trailing one to trim back off afterwards.
                if (cases.Count > 0) source.AppendLine();

                var name = Unique(used, method.Target.Method.Name);
                Case(source, method.Target, observation, name);
                cases.Add(new GeneratedCase(name, method.Target, observation));
            }
        }

        source.AppendLine("}");

        return new GeneratedSuite(source.ToString(), cases);
    }

    private static string Unique(Dictionary<string, int> used, string name)
    {
        var seen = used.GetValueOrDefault(name);
        used[name] = seen + 1;
        return $"{name}_{seen + 1}";
    }

    private static void Case(
        StringBuilder source, Target target, Observation observation, string testName)
    {
        var method = target.Method;
        var arguments = string.Join(", ", observation.Arguments.Select(Values.Literal));

        source.AppendLine("    [Fact]");
        source.AppendLine($"    public void {testName}()");
        source.AppendLine("    {");

        var receiver = method.IsStatic
            ? Values.Name(method.DeclaringType!)
            : "subject";

        if (!method.IsStatic)
            source.AppendLine($"        var subject = new {Values.Name(method.DeclaringType!)}();");

        var call = $"{receiver}.{method.Name}({arguments})";

        switch (observation.Shape)
        {
            case ResultShape.Threw:
                // The exception type only. Its message is a string somebody
                // will reword during the migration, and pinning it would turn a
                // safety net into an obstacle.
                //
                // Written from the recorded name rather than resolved through
                // Type.GetType, which only finds types in this assembly and in
                // the core library, and would quietly downgrade a custom
                // exception to the base class.
                source.AppendLine(
                    $"        Assert.Throws<global::{observation.ExceptionType}>(() => {call});");
                break;

            case ResultShape.Json:
                source.AppendLine($"        var result = {call};");
                source.AppendLine();
                source.AppendLine($"        Assert.Equal({Values.Literal(observation.Rendered)},");
                source.AppendLine("            JsonSerializer.Serialize(result));");
                break;

            default:
                source.AppendLine($"        var result = {call};");
                source.AppendLine();

                // Assert.Equal(null, x) compiles and passes, and reads as an
                // oversight in a file somebody is already suspicious of.
                source.AppendLine(observation.Rendered is "null"
                    ? "        Assert.Null(result);"
                    : $"        Assert.Equal({observation.Rendered}, result);");
                break;
        }

        source.AppendLine("    }");
    }
}
